[package]
name = "tmpfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuse = "0.3.1"
libc = "0.2.42"
time = "0.1.40"
log = "0.4.5"
env_logger = "0.6"
threadpool = "1.7"